64 setup callbacks in toolkit
BIGmama-technology/Hyko-toolkit pull request #67
Opened 2024-05-19 09:33 UTC by yous92

#64

2024-05-20 10:58 UTC, 1hachem approved these changes
looking good 🌵 please just follow my comment and update

2024-05-20 10:58 UTC, 1hachem commented on hyko_toolkit/io/sheets/metadata.py
> +        data = response.json()
please add a `pydantic` model for this and validate the response

2024-05-21 13:51 UTC, strlrd-29 requested changes

2024-05-21 13:51 UTC, strlrd-29 commented on hyko_toolkit/io/csv/metadata.py
> +        )
This should not append to the already existing outputs of the metadata, instead it should first clear up the outputs and then start appending to them

2024-05-27 19:09 UTC, merged